# Today I learned how to make variables, and I figured how to work them and make really questions or comments based on previous answers, and I also figured that we couldn't put spaces between the word, but instead, you can use underscores.
myName = input("What's you name? ")
myAge = input("How old are you? ")
print("Gee, that's REALLY OLD")
replit = input("Do you like Replit? ")
print("OF COURSE YOU DO!")
print()
print("So, you are")
print(myName)
print("and are the ripe old age of")
print(myAge)
print("and clearly think that Replit is")
print(replit)

myLunch = input("What are you having for lunch? ")
print("Hmm, it sounds like you really should just order")
print(myLunch)
print("as soon as possible!")

print("Definitely not a Phishing Scam")
print()
myName=input("Your Name")
print("Thanks for logging in")
print(myName)
cardNumber=input("What is your credit card number?")
print("Thanks, I definitely wont put")
print(cardNumber)
print("into Amazon and order anything weird")
print()
print("Promise")
maidenName=input("What is your Mother's maiden name? ")
print()
print("That's cool, I just wanted to know that")
print(maidenName)
print("was your Mum's maiden name. Not because the bank requested it or anything, honest.")

Name=input("What is your name?")
print("Cool Name", Name)
Food=input("What is you favorite food?")
Music=input("What is your favorite music?")
Live=input("Where do you live?")
print()
print("So you name is", Name, "and you like", Food, "and", Music, "and you live in", Live)
